### ISSUE TITLE
Update download page and remove CLDF download ...

### ISSUE THREAD

**Issue by xrotwang** [clld/ids#11]
... instead linking via DOI to the archived datasets on Zenodo.

**Comment by Bibiko** [comment]
What would be the best strategy to store this info which datasets were imported? `Contribution` is used for any single `dictionary`. A separate new table?

**Comment by xrotwang** [comment]
hm. or we just add a property `Contribution.doi` and then list the distinct DOIs with language if only one, as `IDS` if more?

**Comment by Bibiko** [comment]
sounds good - maybe additionally we'd add `Contribution.title` to not only list a DOI but also a name for it.

**Comment by xrotwang** [comment]
Yes, good idea - and available from zenodo as well.
