### ISSUE TITLE
Most of the Punjabi entries are incorrect

### ISSUE THREAD

**Issue by bgo-eiu** [clld/ids#25]
Referring to the data set here:
https://ids.clld.org/contributions/707

There are several problems apparent with this data:
* Many of the words are Hindustani (Hindi/Urdu) words, not Punjabi. While some Hindi/Urdu words have been loaned into Punjabi, there are words here which are never or rarely used in the language as well as unadapted pronunciations (despite being closely related, Hindi loans do need to be adapted to be pronounceable in Punjabi). bāraśa for example is just plain Hindi https://ids.clld.org/units/707-83 The Punjabi adaptation of the loan word is at least included in this case would be pronounced baraśā, as seen here in the entry for it in [Salahuddin's Punjabi dictionary](https://dsal.uchicago.edu/cgi-bin/app/salah-ud-din_query.py?qs=%D8%A8%D8%B1%D8%B4%D8%A7&searchhws=yes&matchtype=exact ). [māmū](https://ids.clld.org/valuesets/2-511-707) is another Hindi word as an example, the Punjabi loan of this word is adapted as māmūṁ. [pasinā ānā](https://ids.clld.org/valuesets/4-550-707) would be an example of a Hindi phrase which does not even have a Punjabi counterpart--verb stems never attach to suffixes like this in the language as a rule, using ānā (without a retroflex nasal at that) is never done in Punjabi.
* Homorganic nasals are a major feature of Punjabi pronunciation and can form distinctions between words. They have been omitted in transcriptions here in the majority of words where they occur.
* The writing of the inherent vowel in the final position in phonemic transcriptions is unconventional. This was not even done for the Hindi dictionary so I am not sure why it was done here. A vocalic release is common at the end of Punjabi words but this is conditioned by the context of a sentence.
* It appears as if an attempt has been made to represent the change in the expression of consonants due to tonality, but it has not been applied consistently. "bh" for example is always a precursor to tonogenesis and the corresponding aspirated consonant has been dropped from the language's phonemic inventory. However, it is transcribed here as "p" in some places and "bh" in others (seemingly the "bh" words seem concentrated in those which are Hindi words not used in Punjabi).
* The tonal words do not contain any diacritics indicating which tone is present. This makes transcribing the consonant change in some cases more confusing.
* Schwa deletion is a regular phenomenon in Punjabi. It is not indicated where it occurs here. "to do" is karnā, not karanā.
* Gemination is also a significant feature of the language, forming many minimal pairs to distinguish words and an important part of the verb conjugation paradigm. It is also a shibboleth for identifying Punjabi origin loans in Hindi as these were simplified in inherited Hindustani words. These are not indicated in nearly every word they are supposed to occur here.
* There are a number of transcriptions which express pronunciations which are non-viable in Punjabi. In some cases, we see karaṇā for example. ṇ can never follow r in Punjabi as a rule, even with the inherent vowel as a liaison. Occasionally in older texts this sequence is seen in spellings, but this is a tendency of Gurmukhi to use morphophonemic spellings in verb forms; that is, preserving the spellings of the constituents of the verb inflection paradigm even where it goes against actual pronunciation. (This helps distinguish homographs as well as easily distinguish verbs as a part of speech).
* For many concepts, there is a very obvious or common word for that concept in Punjabi which is not included. dandruff is "kar" in Punjabi for example, and yet there are two words for dandruff here which most speakers have never used.

---

I would like to submit a corrected word list for Punjabi if it would be accepted. If so, should I put it here, or email it to the email address recently added to the init script?

**Comment by bgo-eiu** [comment]
I will add that if it is not viable to accept a replacement list for Punjabi, this dictionary should be removed from the site altogether as it cannot be considered representative of the language.

**Comment by xrotwang** [comment]
The list will be re-checked, see
https://github.com/intercontinental-dictionary-series/ids/issues/30

Thanks for bringing this to our attention!
